[toolchain]
components = [
  "rustfmt",
  "clippy",
  "llvm-tools-preview",
  "rust-analyzer",
  # "rustc-codegen-cranelift-preview",
  # "aarch64-linux-android",
  # "armv7-linux-androideabi",
  # "i686-linux-android",
  "x86_64-linux-android",
]
